# Generated by Django 5.2.9 on 2025-12-10 14:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('data', models.DateField()),
                ('cor', models.CharField(default='green', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Novidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=200)),
                ('avatar', models.CharField(default='📢', max_length=10)),
                ('cor_avatar', models.CharField(default='blue', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Novidade',
                'verbose_name_plural': 'Novidades',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('foto_url', models.URLField(default='https://images.icon-icons.com/2483/PNG/512/user_icon_149851.png', verbose_name='URL da Foto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
                ('descricao', models.TextField(blank=True, max_length=300, verbose_name='Descrição')),
                ('cor', models.CharField(default='#808080', max_length=7, verbose_name='Cor (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('descricao', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restrito', 'Restrito por Cargo')], default='publico', max_length=10, verbose_name='Tipo de Canal')),
                ('avatar', models.CharField(default='💬', max_length=10, verbose_name='Avatar (emoji)')),
                ('cor_avatar', models.CharField(default='blue', max_length=20, verbose_name='Cor do Avatar')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('cargos_permitidos', models.ManyToManyField(blank=True, help_text='Cargos que podem acessar este canal (apenas para canais restritos)', related_name='canais', to='core.cargo', verbose_name='Cargos Permitidos')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('descricao', models.TextField(blank=True, max_length=300, verbose_name='Descrição')),
                ('cor', models.CharField(default='#808080', max_length=7, verbose_name='Cor (hex)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10, verbose_name='Status')),
                ('motivo_recusa', models.TextField(blank=True, max_length=500, verbose_name='Motivo da Recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_requests_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Cargo',
                'verbose_name_plural': 'Solicitações de Cargo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('descricao', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restrito', 'Restrito por Cargo')], default='publico', max_length=10, verbose_name='Tipo de Canal')),
                ('avatar', models.CharField(default='💬', max_length=10, verbose_name='Avatar (emoji)')),
                ('cor_avatar', models.CharField(default='blue', max_length=20, verbose_name='Cor do Avatar')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10, verbose_name='Status')),
                ('motivo_recusa', models.TextField(blank=True, max_length=500, verbose_name='Motivo da Recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('cargos_permitidos', models.ManyToManyField(blank=True, related_name='chat_requests', to='core.cargo', verbose_name='Cargos Permitidos')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Chat',
                'verbose_name_plural': 'Solicitações de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuicao', models.IntegerField()),
                ('equilibrio', models.IntegerField()),
                ('aplicacao', models.IntegerField()),
                ('material', models.IntegerField()),
                ('distribuicao', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='MembroCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('moderador', 'Moderador'), ('membro', 'Membro')], default='membro', max_length=10, verbose_name='Papel no Canal')),
                ('entrou_em', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('ultima_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Última leitura')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_membros', to='core.canal', verbose_name='Canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_canal', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do Canal',
                'verbose_name_plural': 'Membros dos Canais',
                'ordering': ['canal', '-entrou_em'],
                'unique_together': {('usuario', 'canal')},
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='membros',
            field=models.ManyToManyField(related_name='canais_membro', through='core.MembroCanal', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='mensagens/arquivos/', verbose_name='Arquivo anexo')),
                ('editada', models.BooleanField(default=False, verbose_name='Editada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.canal', verbose_name='Canal')),
                ('responde_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='core.mensagem', verbose_name='Responde a')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem', 'Nova Mensagem'), ('mencao', 'Menção'), ('canal', 'Novo Canal'), ('cargo', 'Novo Cargo'), ('sistema', 'Sistema')], max_length=10, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesquisa', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to=settings.AUTH_USER_MODEL)),
                ('usuario_pesquisado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foi_pesquisado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesquisa Recente',
                'verbose_name_plural': 'Pesquisas Recentes',
                'ordering': ['-data_pesquisa'],
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(related_name='professores', to='core.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.IntegerField(blank=True, null=True)),
                ('metodos', models.IntegerField(blank=True, null=True)),
                ('relacionamento', models.IntegerField(blank=True, null=True)),
                ('compatibilidade', models.IntegerField(blank=True, null=True)),
                ('clareza', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='core.mensagem', verbose_name='Mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['created_at'],
                'unique_together': {('mensagem', 'usuario', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores_list', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_usuarios', to='core.cargo', verbose_name='Cargo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cargos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cargo do Usuário',
                'verbose_name_plural': 'Cargos dos Usuários',
                'ordering': ['usuario', 'cargo'],
                'unique_together': {('usuario', 'cargo')},
            },
        ),
    ]
